/**
 * src/payment/signedReceipts.ts — cryptographically signed offers & receipts.
 *
 * Upgrades Roam402's receipt story from headers to verifiable attestations:
 * the x402 offer-receipt extension signs every 402 offer and every
 * settlement receipt as a JWS (EdDSA/Ed25519, Workers-native WebCrypto).
 * The kid is a did:jwk — the verifying public key travels inside the key id,
 * so anyone can verify a Roam402 receipt offline with no key registry.
 *
 * Enabled only when the RECEIPT_SIGNING_JWK secret is present (a full
 * private Ed25519 JWK, generated by scripts/new-receipt-key.ts); absent →
 * the gateway runs exactly as before. Key material never leaves this module.
 */

import {
  createOfferReceiptExtension,
  createJWSOfferReceiptIssuer,
  declareOfferReceiptExtension,
  type JWSSigner,
  type OfferReceiptDeclaration,
} from "@x402/extensions";

interface Ed25519Jwk {
  kty: string;
  crv: string;
  x: string;
  d?: string;
}

const b64url = (bytes: Uint8Array): string =>
  btoa(String.fromCharCode(...bytes)).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");

/** did:jwk of the PUBLIC half — verifiers derive the key from the kid itself. */
function didJwkKid(jwk: Ed25519Jwk): string {
  const pub = JSON.stringify({ kty: jwk.kty, crv: jwk.crv, x: jwk.x });
  return `did:jwk:${b64url(new TextEncoder().encode(pub))}#0`;
}

export interface SignedReceipts {
  /** Resource-server extension — register on the x402ResourceServer. */
  extension: ReturnType<typeof createOfferReceiptExtension>;
  /** Per-route declaration — spread into each paid route's `extensions`. */
  routeExtensions: Record<string, OfferReceiptDeclaration>;
  kid: string;
}

/** Parse + import the signing key; null (feature off) on absent/invalid key. */
export async function loadSignedReceipts(jwkJson: string | undefined): Promise<SignedReceipts | null> {
  if (!jwkJson) return null;

  let jwk: Ed25519Jwk;
  try {
    jwk = JSON.parse(jwkJson) as Ed25519Jwk;
  } catch {
    return null;
  }
  if (jwk.kty !== "OKP" || jwk.crv !== "Ed25519" || !jwk.d) return null;

  const key = await crypto.subtle.importKey(
    "jwk",
    jwk as JsonWebKey,
    { name: "Ed25519" },
    false,
    ["sign"]
  );

  const kid = didJwkKid(jwk);
  const signer: JWSSigner = {
    kid,
    format: "jws",
    algorithm: "EdDSA",
    sign: async (payload: Uint8Array) =>
      b64url(new Uint8Array(await crypto.subtle.sign("Ed25519", key, payload as BufferSource))),
  };

  return {
    extension: createOfferReceiptExtension(createJWSOfferReceiptIssuer(kid, signer)),
    // includeTxHash: receipts bind to the on-chain settlement — that
    // verifiability IS the product; we have no buyer-privacy reason to omit it.
    routeExtensions: declareOfferReceiptExtension({ includeTxHash: true }),
    kid,
  };
}
