/**
 * src/catalog.ts — typed access to the generated route table.
 *
 * catalog/routes.json is GENERATED by scripts/generate-catalog.ts from the
 * Agents-Trust census (public API — no repo coupling). It is committed so a
 * deploy is reproducible; regeneration is a script run + review + redeploy.
 */

import routesJson from "../catalog/routes.json";

export interface WrappedRoute {
  /** Stable slug — becomes the path segment /r/{slug}. */
  slug: string;
  /** Origin service canonical domain (agents-trust identity). */
  service: string;
  /** Agents-Trust trust tier at generation time. */
  tier: string;
  /** Census category (e.g. market_data, ai_inference). */
  category: string;
  method: "GET" | "POST";
  originUrl: string;
  originPriceUsd: number;
  /** Our price (origin × margin + fee) — precomputed at generation. */
  roamPriceUsd: number;
  /** Concrete Bazaar description: what the caller actually receives. */
  description: string;
}

export interface Catalog {
  generatedAt: string;
  source: string;
  routes: WrappedRoute[];
}

export const catalog: Catalog = routesJson as Catalog;

const bySlug = new Map(catalog.routes.map((r) => [r.slug, r]));

/** Slug of the injected cross-chain loop-test route (testnet only). */
export const TEST_ROUTE_SLUG = "test-sepolia";

/** Synthetic route for the loop test — exists only when testOriginUrl is set. */
export function testRoute(testOriginUrl: string | undefined): WrappedRoute | undefined {
  if (!testOriginUrl) return undefined;
  return {
    slug: TEST_ROUTE_SLUG,
    service: "mock-origin.sepolia",
    tier: "Test",
    category: "loop-test",
    method: "GET",
    originUrl: testOriginUrl,
    originPriceUsd: 0.001,
    roamPriceUsd: 0.001,
    description:
      "LOOP TEST (testnet only): pays a mock origin $0.001 USDC on Base Sepolia and returns its response — proves the full cross-chain path with faucet money.",
  };
}

export function findRoute(slug: string, testOriginUrl?: string): WrappedRoute | undefined {
  return bySlug.get(slug) ?? (slug === TEST_ROUTE_SLUG ? testRoute(testOriginUrl) : undefined);
}
