/**
 * src/catalog.ts — typed access to the generated route table.
 *
 * catalog/routes.json is GENERATED by scripts/generate-catalog.ts from the
 * Agents-Trust census (public API — no repo coupling). It is committed so a
 * deploy is reproducible; regeneration is a script run + review + redeploy.
 */

import routesJson from "../catalog/routes.json";

export interface WrappedRoute {
  /** Stable slug — becomes the path segment /r/{slug}. */
  slug: string;
  /** Origin service canonical domain (agents-trust identity). */
  service: string;
  /** Agents-Trust trust tier at generation time. */
  tier: string;
  method: "GET" | "POST";
  originUrl: string;
  originPriceUsd: number;
  /** Our price (origin × margin + fee) — precomputed at generation. */
  roamPriceUsd: number;
  /** Concrete Bazaar description: what the caller actually receives. */
  description: string;
}

export interface Catalog {
  generatedAt: string;
  source: string;
  routes: WrappedRoute[];
}

export const catalog: Catalog = routesJson as Catalog;

const bySlug = new Map(catalog.routes.map((r) => [r.slug, r]));

export function findRoute(slug: string): WrappedRoute | undefined {
  return bySlug.get(slug);
}
